import { Poppins } from "next/font/google";
import "./globals.css";
import dynamic from 'next/dynamic';
import { AppProvider } from "@/app/context/appContext";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "graphQL",
  description: "Generated by create next app",
};

const MyComponent = dynamic(() => import('./components/Cursor'), {
  ssr: false,
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={poppins.className}>
        <MyComponent />
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
